server:
  port: 6004

spring:
  application:
    name: demo-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};endTimeAsDateTime=false;encrypt=false;trustServerCertificate=false;
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2019Dialect
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth0.diu.edu.bd/realms/demo

security:
  ignored: '/**'

springdoc:
  swagger-ui:
    path: '/swagger-ui'

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://demo:password@localhost:9761/eureka
