server:
  port: 6004

spring:
  application:
    name: demo-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=demo;sendTimeAsDateTime=false;encrypt=false;trustServerCertificate=false;
    username: sa
    password: Diu$1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2019Dialect
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth0.diu.edu.bd/realms/demo

security:
  ignored: '/**'

springdoc:
  swagger-ui:
    path: '/swagger-ui'

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://demo:password@localhost:9761/eureka
